//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBill
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyInfo
    {
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string CompanyHOAddress1 { get; set; }
        public string CompanyHOAddress2 { get; set; }
        public string CompanyHOAddress3 { get; set; }
        public string CompanyHOPINCode { get; set; }
        public string CompanyBOAddress1 { get; set; }
        public string CompanyBOAddress2 { get; set; }
        public string CompanyBOAddress3 { get; set; }
        public string CompanyBOPINCode { get; set; }
        public string CompanyMobileNo { get; set; }
        public string CompanyEMailId { get; set; }
        public string CompanyGSTN { get; set; }
        public string CompanyBankName { get; set; }
        public string CompanyBankACNo { get; set; }
        public string CompanyBankIFSCCode { get; set; }
        public string CompanyBankBranch { get; set; }
        public string CompanyPAN { get; set; }
    }
}
