//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBill
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaTax
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaTax()
        {
            this.InvoiceSubs = new HashSet<InvoiceSub>();
            this.PrMasters = new HashSet<PrMaster>();
        }
    
        public int TaxId { get; set; }
        public string TaxName { get; set; }
        public string CGSTCaption { get; set; }
        public Nullable<decimal> CGSTTaxRate { get; set; }
        public string SGSTCaption { get; set; }
        public Nullable<decimal> SGSTTaxRate { get; set; }
        public string IGSTCaption { get; set; }
        public Nullable<decimal> IGSTTaxRate { get; set; }
        public string UGSTCaption { get; set; }
        public Nullable<decimal> UGSTTaxRate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceSub> InvoiceSubs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrMaster> PrMasters { get; set; }
    }
}
